split:
  full_data_path: assets/data/raw/train.csv
  train_data_path: assets/data/processed/final_train.csv
  eval_data_path: assets/data/processed/final_test.csv
train:
  username: ayah.elghaysh.12345
  repo: eZZ_ML_Practice
  train_data_path: assets/data/processed/final_train.csv
  eval_data_path: assets/data/processed/final_test.csv
  model_path: assets/models/model.pkl
evaluate:
  eval_data_path: assets/data/processed/final_test.csv
  model_path: assets/models/model.pkl
  validation_file: assets/results/validation_perf.json